[2024-02-14 09:47:26,191: INFO: main: welcome to our logs]
[2024-02-14 15:41:43,644: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-14 15:41:43,645: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-14 15:41:43,646: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-14 15:41:43,647: INFO: common: created directory at: artifacts]
[2024-02-14 15:41:43,648: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-14 15:41:43,649: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 15:44:47,438: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-14 15:44:48,154: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-19 15:18:21,202: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-19 15:18:21,222: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-19 15:18:21,225: INFO: common: created directory at: artifacts]
[2024-02-19 15:18:21,228: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-19 15:18:37,173: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-19 15:31:31,799: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-19 15:31:31,803: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-19 15:31:31,806: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-19 15:31:31,808: INFO: common: created directory at: artifacts]
[2024-02-19 15:31:31,811: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-19 15:31:31,814: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-19 15:31:46,220: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-19 15:31:47,789: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-19 15:31:47,790: INFO: main: *******************]
[2024-02-19 15:31:47,791: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-19 15:31:47,794: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-19 15:31:47,797: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-19 15:31:47,799: INFO: common: created directory at: artifacts]
[2024-02-19 15:31:47,801: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-19 15:31:48,465: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-19 15:31:49,104: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-22 13:14:53,672: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-22 13:14:53,696: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-22 13:14:53,699: INFO: common: created directory at: artifacts]
[2024-02-22 13:14:53,703: INFO: common: created directory at: artifacts\training]
[2024-02-22 13:27:54,364: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-22 13:27:54,367: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-22 13:27:54,370: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-22 13:27:54,408: INFO: common: created directory at: artifacts]
[2024-02-22 13:27:54,410: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-22 13:27:54,412: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 13:30:23,798: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-22 13:30:25,332: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-22 13:30:25,333: INFO: main: *******************]
[2024-02-22 13:30:25,334: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-22 13:30:25,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-22 13:30:25,342: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-22 13:30:25,346: INFO: common: created directory at: artifacts]
[2024-02-22 13:30:25,347: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-22 13:30:26,128: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-22 13:30:26,487: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-22 13:30:26,488: INFO: main: *******************]
[2024-02-22 13:30:26,489: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-22 13:30:26,491: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-22 13:30:26,494: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-22 13:30:26,496: INFO: common: created directory at: artifacts]
[2024-02-22 13:30:26,498: INFO: common: created directory at: artifacts\training]
[2024-02-22 13:31:11,789: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-07 12:22:55,096: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-07 12:22:55,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:22:55,120: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:22:55,121: INFO: common: created directory at: artifacts]
[2024-03-07 12:22:55,122: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-07 12:22:55,123: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:25:04,072: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-07 12:25:05,534: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-07 12:25:05,535: INFO: main: *******************]
[2024-03-07 12:25:05,536: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-07 12:25:05,539: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:25:05,543: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:25:05,545: INFO: common: created directory at: artifacts]
[2024-03-07 12:25:05,547: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-07 12:25:06,443: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-07 12:25:06,784: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-07 12:25:06,785: INFO: main: *******************]
[2024-03-07 12:25:06,786: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-07 12:25:06,789: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-07 12:25:06,790: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-07 12:25:06,792: INFO: common: created directory at: artifacts]
[2024-03-07 12:25:06,794: INFO: common: created directory at: artifacts\training]
[2024-03-07 12:39:19,868: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 09:46:25,762: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 09:46:25,770: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 09:46:25,774: INFO: common: created directory at: artifacts]
[2024-03-08 09:46:42,073: INFO: common: json file saved at: scores.json]
[2024-03-08 09:46:46,850: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-08 09:46:47,837: INFO: builder_impl: Assets written to: C:\Users\hp\AppData\Local\Temp\tmpv69r80gu\model\data\model\assets]
[2024-03-08 10:30:27,514: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 10:30:27,516: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 10:30:27,518: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 10:30:27,518: INFO: common: created directory at: artifacts]
[2024-03-08 10:30:27,519: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 10:30:27,520: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 10:36:46,494: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 10:36:47,376: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-08 10:36:47,376: INFO: main: *******************]
[2024-03-08 10:36:47,377: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-08 10:36:47,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 10:36:47,395: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 10:36:47,397: INFO: common: created directory at: artifacts]
[2024-03-08 10:36:47,398: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-08 10:36:47,958: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-08 10:36:48,210: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-08 10:36:48,210: INFO: main: *******************]
[2024-03-08 10:36:48,211: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-08 10:36:48,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 10:36:48,214: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 10:36:48,215: INFO: common: created directory at: artifacts]
[2024-03-08 10:36:48,216: INFO: common: created directory at: artifacts\training]
[2024-03-08 10:51:47,006: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 10:51:47,007: INFO: main: *******************]
[2024-03-08 10:51:47,007: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-08 10:51:47,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 10:51:47,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 10:51:47,014: INFO: common: created directory at: artifacts]
[2024-03-08 10:52:02,322: INFO: common: json file saved at: scores.json]
[2024-03-08 10:52:02,324: INFO: common: json file saved at: scores.json]
[2024-03-08 10:52:02,324: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-08 12:10:50,536: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 12:10:50,537: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 12:10:54,911: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 12:10:54] "GET / HTTP/1.1" 200 -]
[2024-03-08 12:11:14,872: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-03-08 12:11:14,957: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 12:11:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 12:14:46,906: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 12:14:46,907: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 12:14:48,817: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 12:14:48] "GET / HTTP/1.1" 200 -]
[2024-03-08 12:14:53,711: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "artifacts\training\model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\artifacts	raining\model.h5
[2024-03-08 12:14:53,724: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 12:14:53] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 12:16:59,937: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 12:16:59,938: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 12:17:02,016: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 12:17:02] "GET / HTTP/1.1" 200 -]
[2024-03-08 12:17:06,492: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 19, in predict
    model = tf.keras.models.load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\artifacts\training\model.h5
[2024-03-08 12:17:06,505: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 12:17:06] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 15:35:53,878: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:35:53,879: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:35:57,369: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:35:57] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:36:03,229: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 19, in predict
    test_image = image.load_img(imagename, target_size = (224,224))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\artifacts\training\model.h5
[2024-03-08 15:36:03,236: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:36:03] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 15:38:24,189: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:38:24,192: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:38:27,834: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:38:27] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:38:35,449: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-03-08 15:38:35,466: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:38:35] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 15:40:31,046: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:40:31,047: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:40:32,586: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:40:32] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:40:38,834: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:40:38] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:40:52,822: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:40:52] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:41:02,821: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:41:02] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:41:55,368: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:41:55,369: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:41:57,625: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:41:57] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:42:05,872: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:42:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:42:31,445: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:42:31,446: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:42:33,123: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:42:33] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:42:39,324: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:42:39] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:42:50,972: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:42:50] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:44:15,055: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:44:15,056: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:44:16,810: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:44:16] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:44:27,059: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:44:27] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:44:41,821: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:44:41] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:46:18,247: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:46:18,248: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:46:22,163: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:46:22] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:46:28,610: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:46:28] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 15:47:43,386: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 15:47:43,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 15:47:43,424: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 15:47:43,425: INFO: common: created directory at: artifacts]
[2024-03-08 15:47:43,426: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 15:47:43,428: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 15:49:24,742: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:49:24,743: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:49:26,992: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:49:26] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:49:37,681: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 15:49:37,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 15:49:37,687: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 15:49:37,690: INFO: common: created directory at: artifacts]
[2024-03-08 15:49:37,691: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 15:49:37,692: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 15:50:29,584: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 15:50:29,585: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 15:50:31,419: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:50:31] "GET / HTTP/1.1" 200 -]
[2024-03-08 15:50:34,017: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 15:50:34,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 15:50:34,024: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 15:50:34,026: INFO: common: created directory at: artifacts]
[2024-03-08 15:50:34,027: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 15:50:34,029: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 15:50:44,295: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:50:44] "GET /train HTTP/1.1" 200 -]
[2024-03-08 15:50:44,371: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 15:50:44] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-03-08 15:52:51,501: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 15:52:53,241: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-08 15:53:10,895: INFO: stage_02_prepare_base_model: *******************]
[2024-03-08 15:53:10,896: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-08 15:53:10,898: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 15:53:10,901: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 15:53:10,902: INFO: common: created directory at: artifacts]
[2024-03-08 15:53:10,905: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-08 15:53:11,526: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-08 15:53:11,866: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-08 15:53:21,693: INFO: stage_03_model_training: *******************]
[2024-03-08 15:53:21,694: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 15:53:21,697: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 15:53:21,700: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 15:53:21,701: INFO: common: created directory at: artifacts]
[2024-03-08 15:53:21,703: INFO: common: created directory at: artifacts\training]
[2024-03-08 16:04:13,218: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 16:04:24,221: INFO: stage_04_model_evaluation: *******************]
[2024-03-08 16:04:24,222: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-08 16:04:24,225: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 16:04:24,228: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 16:04:24,230: INFO: common: created directory at: artifacts]
[2024-03-08 16:04:39,182: INFO: common: json file saved at: scores.json]
[2024-03-08 16:04:39,183: INFO: common: json file saved at: scores.json]
[2024-03-08 16:04:39,184: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-08 16:04:40,669: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:04:40] "GET /train HTTP/1.1" 200 -]
[2024-03-08 16:05:07,985: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:05:07] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:05:15,381: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:05:15] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:07:57,907: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:07:57,908: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:07:59,648: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:07:59] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:08:04,962: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result[0] == 1:
       ~~~~~~^^^
IndexError: invalid index to scalar variable.
[2024-03-08 16:08:04,973: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:08:04] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 16:08:27,205: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:08:27] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:08:32,673: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 25, in predict
    if result[0] == 1:
       ~~~~~~^^^
IndexError: invalid index to scalar variable.
[2024-03-08 16:08:32,691: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:08:32] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 16:08:49,028: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:08:49,029: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:08:52,697: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:08:52] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:09:00,075: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:09:00] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:09:25,321: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:09:25] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:09:49,316: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:09:49,317: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:09:51,934: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:09:51] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:09:58,049: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:09:58] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:13:44,720: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:13:44,722: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:14:25,592: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:14:25] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:14:33,358: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:14:33] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:17:19,567: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:17:19,568: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:17:21,888: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:17:21] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:17:48,532: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:17:48] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:18:22,066: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:18:22,067: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:18:24,967: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:18:24] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:18:31,443: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\prediction.py", line 23, in predict
    logits = model.predict(test_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Temp\__autograph_generated_filexrwleczi.py", line 18, in tf__predict_function
    raise
ValueError: in user code:

    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 2111, in predict_step
        return self(x, training=False)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 224, 224, 3), found shape=(32, 224, 3)

[2024-03-08 16:18:31,458: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:18:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-03-08 16:19:38,308: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:19:38,309: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:19:53,094: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:19:53] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:20:04,945: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:20:04] "GET /train HTTP/1.1" 200 -]
[2024-03-08 16:20:39,042: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:20:39,044: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:20:42,009: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:20:42] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:21:01,633: INFO: stage_03_model_training: *******************]
[2024-03-08 16:21:01,634: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 16:21:01,636: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 16:21:01,639: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 16:21:01,641: INFO: common: created directory at: artifacts]
[2024-03-08 16:21:01,643: INFO: common: created directory at: artifacts\training]
[2024-03-08 16:21:48,414: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 16:21:59,592: INFO: stage_04_model_evaluation: *******************]
[2024-03-08 16:21:59,593: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-08 16:21:59,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 16:21:59,601: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 16:21:59,602: INFO: common: created directory at: artifacts]
[2024-03-08 16:22:15,018: INFO: common: json file saved at: scores.json]
[2024-03-08 16:22:15,019: INFO: common: json file saved at: scores.json]
[2024-03-08 16:22:15,019: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-08 16:22:16,512: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:22:16] "GET /train HTTP/1.1" 200 -]
[2024-03-08 16:22:37,902: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:22:37] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:22:46,069: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:22:46] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:24:05,300: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.11:8080]
[2024-03-08 16:24:05,300: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:24:09,113: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:24:09] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:24:13,787: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:24:13] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:24:30,941: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.11:8080]
[2024-03-08 16:24:30,942: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:24:32,344: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:24:32] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:24:37,855: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:24:37] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:25:52,008: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:25:52,010: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:25:54,126: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:25:54] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:26:11,570: INFO: stage_02_prepare_base_model: *******************]
[2024-03-08 16:26:11,570: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-08 16:26:11,574: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 16:26:11,576: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 16:26:11,577: INFO: common: created directory at: artifacts]
[2024-03-08 16:26:11,578: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-08 16:26:12,082: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-08 16:26:12,306: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-08 16:26:19,043: INFO: stage_03_model_training: *******************]
[2024-03-08 16:26:19,043: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 16:26:19,045: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 16:26:19,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 16:26:19,048: INFO: common: created directory at: artifacts]
[2024-03-08 16:26:19,049: INFO: common: created directory at: artifacts\training]
[2024-03-08 16:26:22,279: ERROR: stage_03_model_training: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 30, in <module>
      obj.main()
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]]
Traceback (most recent call last):
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 30, in <module>
    obj.main()
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\eager\execute.py", line 58, in quick_execute
    except TypeError as e:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 30, in <module>
      obj.main()
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]
[2024-03-08 16:26:23,142: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:26:23] "GET /train HTTP/1.1" 200 -]
[2024-03-08 16:27:12,899: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 16:27:12,900: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:27:16,238: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:27:16] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:27:25,135: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:27:25] "GET /train HTTP/1.1" 200 -]
[2024-03-08 16:42:09,433: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 16:42:09,434: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:42:13,525: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:42:13] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:42:17,990: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:42:17] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:42:47,020: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:42:47] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:42:55,116: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:42:55] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:48:47,230: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 16:48:47,231: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:48:51,362: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:48:51] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:48:57,985: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:48:57] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 16:52:37,158: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 16:52:37,159: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 16:52:39,579: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:52:39] "GET / HTTP/1.1" 200 -]
[2024-03-08 16:52:48,398: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 16:52:48] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 17:42:04,201: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 17:42:04,202: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 17:42:05,741: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:42:05] "GET / HTTP/1.1" 200 -]
[2024-03-08 17:42:11,477: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:42:11] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 17:43:54,269: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 17:43:54,270: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 17:43:56,438: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:43:56] "GET / HTTP/1.1" 200 -]
[2024-03-08 17:44:03,626: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:44:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 17:46:09,423: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 17:46:09,423: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 17:46:10,905: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:46:10] "GET / HTTP/1.1" 200 -]
[2024-03-08 17:46:16,339: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:46:16] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 17:47:42,312: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 17:47:42,312: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 17:47:45,570: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:47:45] "GET / HTTP/1.1" 200 -]
[2024-03-08 17:47:51,262: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:47:51] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 17:51:11,759: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 17:51:11,759: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 17:51:13,539: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:51:13] "GET / HTTP/1.1" 200 -]
[2024-03-08 17:51:18,449: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:51:18] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 17:57:15,604: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 17:57:15,604: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 17:57:39,192: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 17:57:39,193: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 17:57:42,744: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 17:57:42] "GET / HTTP/1.1" 200 -]
[2024-03-08 17:58:02,213: INFO: stage_03_model_training: *******************]
[2024-03-08 17:58:02,213: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 17:58:02,216: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 17:58:02,218: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 17:58:02,219: INFO: common: created directory at: artifacts]
[2024-03-08 17:58:02,220: INFO: common: created directory at: artifacts\training]
[2024-03-08 18:01:38,391: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 18:01:49,569: INFO: stage_04_model_evaluation: *******************]
[2024-03-08 18:01:49,571: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-08 18:01:49,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 18:01:49,578: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 18:01:49,580: INFO: common: created directory at: artifacts]
[2024-03-08 18:02:04,561: INFO: common: json file saved at: scores.json]
[2024-03-08 18:02:04,564: INFO: common: json file saved at: scores.json]
[2024-03-08 18:02:04,564: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-08 18:02:06,027: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:02:06] "GET /train HTTP/1.1" 200 -]
[2024-03-08 18:02:21,675: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:02:21] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:02:32,476: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:02:32] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:02:55,623: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:02:55] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:03:08,314: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:03:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:03:17,853: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:03:17] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:03:28,987: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000177DAF51BC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 18:03:28,996: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:03:28] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:09:25,516: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 18:09:25,518: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:09:27,835: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:09:27] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:11:34,096: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 18:11:34,118: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:11:35,404: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:11:35] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:11:35,424: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:11:35] "[33mGET /loading.gif HTTP/1.1[0m" 404 -]
[2024-03-08 18:11:35,435: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:11:35] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:13:33,036: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 18:13:33,037: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:13:34,581: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:13:34] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:13:42,592: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:13:42] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:13:52,153: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:13:52] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:13:57,500: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:13:57] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:14:03,127: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:14:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:14:59,623: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 18:14:59,624: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:15:01,616: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:15:01] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:15:16,851: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:15:16] "GET /train HTTP/1.1" 200 -]
[2024-03-08 18:15:49,074: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:15:49] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:15:57,913: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:15:57] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:16:03,877: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:16:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:16:53,796: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 18:16:53,796: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:16:55,196: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:16:55] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:17:21,597: INFO: stage_03_model_training: *******************]
[2024-03-08 18:17:21,598: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 18:17:21,600: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 18:17:21,603: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 18:17:21,605: INFO: common: created directory at: artifacts]
[2024-03-08 18:17:21,609: INFO: common: created directory at: artifacts\training]
[2024-03-08 18:21:43,548: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 18:21:54,952: INFO: stage_04_model_evaluation: *******************]
[2024-03-08 18:21:54,954: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-08 18:21:54,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 18:21:54,960: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 18:21:54,962: INFO: common: created directory at: artifacts]
[2024-03-08 18:22:10,648: INFO: common: json file saved at: scores.json]
[2024-03-08 18:22:10,651: INFO: common: json file saved at: scores.json]
[2024-03-08 18:22:10,651: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-08 18:22:12,126: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:22:12] "GET /train HTTP/1.1" 200 -]
[2024-03-08 18:22:27,721: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:22:27] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:22:37,350: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:22:37] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:22:46,207: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:22:46] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:22:52,990: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:22:52] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:23:30,244: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 18:23:30,245: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:23:31,730: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:23:31] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:23:42,068: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:23:42] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:23:52,930: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:23:52] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:24:08,027: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:24:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:27:33,071: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.97.108:5000]
[2024-03-08 18:27:33,072: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:27:35,753: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:27:35] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:27:44,690: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:27:44] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:27:56,186: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:27:56] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:28:27,577: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:28:27] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:28:44,514: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:28:44] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:28:59,445: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000023F00AD2B60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 18:28:59,454: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:28:59] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:29:08,385: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000023F00AD2C00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 18:29:08,395: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:29:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:29:18,223: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:29:18] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 18:30:19,007: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 18:30:19,008: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:30:24,069: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:30:24] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:30:45,654: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:30:45] "GET /train HTTP/1.1" 200 -]
[2024-03-08 18:31:39,507: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-08 18:31:39,509: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 18:31:41,185: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:31:41] "GET / HTTP/1.1" 200 -]
[2024-03-08 18:32:07,387: INFO: stage_03_model_training: *******************]
[2024-03-08 18:32:07,388: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 18:32:07,392: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 18:32:07,395: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 18:32:07,396: INFO: common: created directory at: artifacts]
[2024-03-08 18:32:07,398: INFO: common: created directory at: artifacts\training]
[2024-03-08 18:50:48,891: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-08 18:51:00,781: INFO: stage_04_model_evaluation: *******************]
[2024-03-08 18:51:00,783: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-08 18:51:00,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 18:51:00,789: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 18:51:00,791: INFO: common: created directory at: artifacts]
[2024-03-08 18:51:16,309: INFO: common: json file saved at: scores.json]
[2024-03-08 18:51:16,310: INFO: common: json file saved at: scores.json]
[2024-03-08 18:51:16,310: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-08 18:51:17,879: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 18:51:17] "GET /train HTTP/1.1" 200 -]
[2024-03-08 19:20:24,268: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:20:24] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:20:32,569: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:20:32] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:20:44,349: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:20:44] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:20:53,871: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:20:53] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:00,075: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:00] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:07,126: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020373831BC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 19:21:07,136: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:07] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:12,925: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020373832AC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 19:21:12,934: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:12] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:19,065: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:19] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:27,742: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:27] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:34,065: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:34] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:40,265: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:40] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:49,105: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:49] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:21:51,164: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:51] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:21:51,904: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:51] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:21:52,141: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:52] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:21:58,358: INFO: _internal: 127.0.0.1 - - [08/Mar/2024 19:21:58] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:36:35,048: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-09 08:36:35,049: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-09 08:36:36,778: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:36:36] "GET / HTTP/1.1" 200 -]
[2024-03-09 08:37:02,268: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:37:02] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:37:14,611: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:37:14] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:37:21,145: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:37:21] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:37:27,947: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:37:27] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:37:38,879: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001CBAC5E1BC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-09 08:37:38,886: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:37:38] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:38:43,820: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-09 08:38:43,821: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-09 08:38:46,698: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:38:46] "GET / HTTP/1.1" 200 -]
[2024-03-09 08:38:53,638: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:38:53] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:38:59,333: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:38:59] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:39:05,583: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:39:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:39:42,958: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:39:42] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:39:53,751: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000133813E1BC0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-09 08:39:53,759: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:39:53] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:40:03,147: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000133813E1800> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-09 08:40:03,155: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:40:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:40:11,057: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:40:11] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:40:17,624: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:40:17] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:40:25,683: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:40:25] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:41:28,497: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-09 08:41:28,501: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-09 08:41:34,551: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:41:34] "GET / HTTP/1.1" 200 -]
[2024-03-09 08:41:42,941: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:41:42] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:41:50,489: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:41:50] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:41:56,396: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:41:56] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:42:05,530: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:42:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:44:52,544: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-09 08:44:52,544: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-09 08:44:54,267: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:44:54] "GET / HTTP/1.1" 200 -]
[2024-03-09 08:45:02,414: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:45:02] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:45:08,431: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:45:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:45:14,888: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:45:14] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:47:17,372: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-09 08:47:17,373: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-09 08:47:19,007: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:47:19] "GET / HTTP/1.1" 200 -]
[2024-03-09 08:47:24,946: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:47:24] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:48:41,818: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-09 08:48:41,819: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-09 08:48:44,419: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:48:44] "GET / HTTP/1.1" 200 -]
[2024-03-09 08:48:50,527: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000011D687D1940> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-09 08:48:50,536: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:48:50] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:49:08,553: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000011D687D1120> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-09 08:49:08,559: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:49:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:49:13,730: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:49:13] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:49:19,179: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:49:19] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:49:26,232: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:49:26] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:49:31,203: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:49:31] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:50:18,152: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.11:5000]
[2024-03-09 08:50:18,152: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-09 08:50:21,115: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:50:21] "GET / HTTP/1.1" 200 -]
[2024-03-09 08:50:27,344: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:50:27] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:51:00,079: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:51:00] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:51:05,583: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:51:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-09 08:51:10,619: INFO: _internal: 127.0.0.1 - - [09/Mar/2024 08:51:10] "POST /predict HTTP/1.1" 200 -]
[2024-03-14 14:29:29,914: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-14 14:29:29,928: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 14:29:29,938: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 14:29:29,939: INFO: common: created directory at: artifacts]
[2024-03-14 14:29:29,940: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-14 14:29:29,942: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 14:30:03,435: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.228.108:5000]
[2024-03-14 14:30:03,436: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-14 14:30:08,564: INFO: _internal: 127.0.0.1 - - [14/Mar/2024 14:30:08] "GET / HTTP/1.1" 200 -]
[2024-03-14 14:30:44,614: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-14 14:30:46,176: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-14 14:30:46,177: INFO: main: *******************]
[2024-03-14 14:30:46,178: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-14 14:30:46,181: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 14:30:46,184: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 14:30:46,186: INFO: common: created directory at: artifacts]
[2024-03-14 14:30:46,187: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-14 14:30:47,016: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-14 14:30:47,367: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-14 14:30:47,368: INFO: main: *******************]
[2024-03-14 14:30:47,368: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-14 14:30:47,370: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-14 14:30:47,372: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-14 14:30:47,375: INFO: common: created directory at: artifacts]
[2024-03-14 14:30:47,377: INFO: common: created directory at: artifacts\training]
[2024-03-14 14:33:27,217: INFO: _internal: 127.0.0.1 - - [14/Mar/2024 14:33:27] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 12:49:59,838: INFO: stage_03_model_training: *******************]
[2024-03-15 12:49:59,838: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-15 12:49:59,850: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 12:49:59,852: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 12:49:59,852: INFO: common: created directory at: artifacts]
[2024-03-15 12:49:59,854: INFO: common: created directory at: artifacts\training]
[2024-03-15 14:17:24,274: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-15 14:17:35,274: INFO: stage_04_model_evaluation: *******************]
[2024-03-15 14:17:35,276: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-15 14:17:35,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 14:17:35,280: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 14:17:35,281: INFO: common: created directory at: artifacts]
[2024-03-15 14:17:48,326: INFO: common: json file saved at: scores.json]
[2024-03-15 14:17:48,329: INFO: common: json file saved at: scores.json]
[2024-03-15 14:17:48,329: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-15 14:21:43,186: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-15 14:21:43,188: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-15 14:22:14,124: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:22:14] "GET / HTTP/1.1" 200 -]
[2024-03-15 14:22:33,552: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:22:33] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:22:47,116: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:22:47] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:24:36,647: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-15 14:24:36,647: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-15 14:24:39,178: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:24:39] "GET / HTTP/1.1" 200 -]
[2024-03-15 14:24:44,407: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:24:44] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:24:53,464: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:24:53] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:25:01,019: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:25:01] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:25:06,700: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:25:06] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:25:12,355: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020BE1689120> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-15 14:25:12,362: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:25:12] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:25:20,020: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000020BE2879F80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-15 14:25:20,026: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:25:20] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 14:59:11,381: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 14:59:11] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 22:58:44,392: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.129.108:5000]
[2024-03-15 22:58:44,393: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-15 22:58:48,312: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:58:48] "GET / HTTP/1.1" 200 -]
[2024-03-15 22:59:02,366: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:59:02] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 22:59:18,854: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:59:18] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 22:59:26,393: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:59:26] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 22:59:33,170: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:59:33] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 22:59:41,388: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001FEE90211C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-15 22:59:41,397: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:59:41] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 22:59:52,618: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001FEEA21A020> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-15 22:59:52,628: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:59:52] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 22:59:59,901: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 22:59:59] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:00:07,960: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:00:07] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:00:20,701: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:00:20] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:00:26,423: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:00:26] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:00:41,812: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:00:41] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:00:50,755: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:00:50] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:00:57,329: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:00:57] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:01:05,614: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:01:05] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:01:17,952: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:01:17] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:01:26,238: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:01:26] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:01:37,186: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:01:37] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:04:56,668: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.129.108:5000]
[2024-03-15 23:04:56,670: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-15 23:05:06,024: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:05:06] "GET / HTTP/1.1" 200 -]
[2024-03-15 23:05:14,200: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:05:14] "POST /predict HTTP/1.1" 200 -]
[2024-03-15 23:06:05,944: INFO: stage_03_model_training: *******************]
[2024-03-15 23:06:05,945: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-15 23:06:05,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-15 23:06:05,952: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-15 23:06:05,953: INFO: common: created directory at: artifacts]
[2024-03-15 23:06:05,955: INFO: common: created directory at: artifacts\training]
[2024-03-15 23:06:11,658: ERROR: stage_03_model_training: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 30, in <module>
      obj.main()
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]]
Traceback (most recent call last):
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 30, in <module>
    obj.main()
  File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\eager\execute.py", line 58, in quick_execute
    except TypeError as e:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'categorical_crossentropy/softmax_cross_entropy_with_logits' defined at (most recent call last):
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 30, in <module>
      obj.main()
    File "C:\Users\hp\OneDrive\Desktop\SGP\Kidney-Disease-Classification-Deep-Learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 1984, in categorical_crossentropy
      return backend.categorical_crossentropy(
    File "C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\backend.py", line 5565, in categorical_crossentropy
      return tf.nn.softmax_cross_entropy_with_logits(
Node: 'categorical_crossentropy/softmax_cross_entropy_with_logits'
logits and labels must be broadcastable: logits_size=[16,3] labels_size=[16,2]
	 [[{{node categorical_crossentropy/softmax_cross_entropy_with_logits}}]] [Op:__inference_train_function_881]
[2024-03-15 23:07:07,756: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.129.108:5000]
[2024-03-15 23:07:07,758: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-15 23:07:10,959: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:07:10] "GET / HTTP/1.1" 200 -]
[2024-03-15 23:07:18,472: INFO: _internal: 127.0.0.1 - - [15/Mar/2024 23:07:18] "POST /predict HTTP/1.1" 200 -]
[2024-03-16 20:54:50,699: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-16 20:54:50,701: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-16 20:54:53,756: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 20:54:53] "GET / HTTP/1.1" 200 -]
[2024-03-16 20:55:10,072: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-16 20:55:10,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 20:55:10,086: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 20:55:10,087: INFO: common: created directory at: artifacts]
[2024-03-16 20:55:10,090: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-16 20:55:10,091: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-16 20:59:19,433: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-16 20:59:20,823: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-16 20:59:20,824: INFO: main: *******************]
[2024-03-16 20:59:20,824: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-16 20:59:20,827: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 20:59:20,830: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 20:59:20,832: INFO: common: created directory at: artifacts]
[2024-03-16 20:59:20,833: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-16 20:59:21,788: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-16 20:59:22,148: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-16 20:59:22,149: INFO: main: *******************]
[2024-03-16 20:59:22,149: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-16 20:59:22,152: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 20:59:22,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 20:59:22,157: INFO: common: created directory at: artifacts]
[2024-03-16 20:59:22,159: INFO: common: created directory at: artifacts\training]
[2024-03-16 21:11:14,873: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-16 21:11:14,873: INFO: main: *******************]
[2024-03-16 21:11:14,874: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-16 21:11:14,875: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-16 21:11:14,877: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-16 21:11:14,878: INFO: common: created directory at: artifacts]
[2024-03-16 21:11:29,645: INFO: common: json file saved at: scores.json]
[2024-03-16 21:11:29,648: INFO: common: json file saved at: scores.json]
[2024-03-16 21:11:29,648: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-16 21:11:30,450: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 21:11:30] "GET /train HTTP/1.1" 200 -]
[2024-03-16 21:11:48,406: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 21:11:48] "GET / HTTP/1.1" 200 -]
[2024-03-16 21:12:08,999: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 21:12:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-16 21:12:17,131: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 21:12:17] "POST /predict HTTP/1.1" 200 -]
[2024-03-16 21:12:24,640: INFO: _internal: 127.0.0.1 - - [16/Mar/2024 21:12:24] "POST /predict HTTP/1.1" 200 -]
[2024-03-18 20:46:23,613: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-18 20:46:23,652: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-18 20:46:25,929: INFO: _internal: 127.0.0.1 - - [18/Mar/2024 20:46:25] "GET / HTTP/1.1" 200 -]
[2024-03-18 20:46:52,621: INFO: _internal: 127.0.0.1 - - [18/Mar/2024 20:46:52] "POST /predict HTTP/1.1" 200 -]
[2024-03-18 20:47:03,748: INFO: _internal: 127.0.0.1 - - [18/Mar/2024 20:47:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-18 20:47:12,785: INFO: _internal: 127.0.0.1 - - [18/Mar/2024 20:47:12] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 09:40:57,463: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-24 09:40:57,464: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-24 09:41:05,346: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 09:41:05] "GET / HTTP/1.1" 200 -]
[2024-03-24 09:41:18,019: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 09:41:18] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 09:53:35,592: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-24 09:53:35,592: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-24 09:53:39,904: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 09:53:39] "GET / HTTP/1.1" 200 -]
[2024-03-24 09:53:47,374: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 09:53:47] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:00:25,271: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-24 10:00:25,272: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-24 10:00:27,273: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:00:27] "GET / HTTP/1.1" 200 -]
[2024-03-24 10:00:35,617: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:00:35] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:00:47,547: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:00:47] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:00:54,399: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:00:54] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:01:01,344: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:01:01] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:02:13,625: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021C793D18A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-24 10:02:13,636: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:02:13] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:02:45,432: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000021C76E2F9C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-24 10:02:45,442: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:02:45] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:39:42,904: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-24 10:39:42,904: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-24 10:39:51,216: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:39:51] "GET / HTTP/1.1" 200 -]
[2024-03-24 10:39:56,968: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:39:56] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:40:02,922: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:40:02] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:40:08,427: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:40:08] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:41:05,893: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-24 10:41:05,894: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-24 10:41:07,312: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:41:07] "GET / HTTP/1.1" 200 -]
[2024-03-24 10:41:12,773: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:41:12] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:41:19,312: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:41:19] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:41:25,991: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:41:25] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:42:11,719: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-24 10:42:11,720: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-24 10:42:12,929: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:42:12] "GET / HTTP/1.1" 200 -]
[2024-03-24 10:42:23,615: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:42:23] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:42:53,659: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 10:42:53] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 10:46:36,333: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-24 10:46:36,343: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-24 10:46:36,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-24 10:46:36,352: INFO: common: created directory at: artifacts]
[2024-03-24 10:46:36,353: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-24 10:46:36,354: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 10:57:06,499: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-24 10:57:07,305: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-24 10:57:07,305: INFO: main: *******************]
[2024-03-24 10:57:07,306: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-24 10:57:07,308: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-24 10:57:07,311: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-24 10:57:07,311: INFO: common: created directory at: artifacts]
[2024-03-24 10:57:07,312: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-24 10:57:07,878: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-24 10:57:08,101: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-24 10:57:08,102: INFO: main: *******************]
[2024-03-24 10:57:08,103: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-24 10:57:08,106: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-24 10:57:08,109: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-24 10:57:08,110: INFO: common: created directory at: artifacts]
[2024-03-24 10:57:08,111: INFO: common: created directory at: artifacts\training]
[2024-03-24 10:59:29,982: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-24 10:59:29,983: INFO: main: *******************]
[2024-03-24 10:59:29,983: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-24 10:59:29,987: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-24 10:59:29,990: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-24 10:59:29,991: INFO: common: created directory at: artifacts]
[2024-03-24 10:59:41,845: INFO: common: json file saved at: scores.json]
[2024-03-24 10:59:41,846: INFO: common: json file saved at: scores.json]
[2024-03-24 10:59:41,847: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-24 11:00:24,505: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.29.55.108:5000]
[2024-03-24 11:00:24,506: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-24 11:00:26,584: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:00:26] "GET / HTTP/1.1" 200 -]
[2024-03-24 11:00:31,662: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:00:31] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 11:00:38,108: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:00:38] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 11:00:43,004: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:00:43] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 11:00:57,916: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:00:57] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 11:01:03,801: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D3EFFB1310> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-24 11:01:03,806: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:01:03] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 11:01:09,779: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D3EFFB1700> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-24 11:01:09,785: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:01:09] "POST /predict HTTP/1.1" 200 -]
[2024-03-24 11:01:15,377: INFO: _internal: 127.0.0.1 - - [24/Mar/2024 11:01:15] "POST /predict HTTP/1.1" 200 -]
[2024-03-26 16:34:12,535: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.158.108:5000]
[2024-03-26 16:34:12,536: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-26 16:34:14,814: INFO: _internal: 127.0.0.1 - - [26/Mar/2024 16:34:14] "GET / HTTP/1.1" 200 -]
[2024-03-26 16:34:14,974: INFO: _internal: 127.0.0.1 - - [26/Mar/2024 16:34:14] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-03-26 16:34:36,274: INFO: _internal: 127.0.0.1 - - [26/Mar/2024 16:34:36] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2024-03-26 16:40:36,229: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.158.108:5000]
[2024-03-26 16:40:36,230: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-26 16:40:38,638: INFO: _internal: 127.0.0.1 - - [26/Mar/2024 16:40:38] "GET / HTTP/1.1" 200 -]
[2024-03-26 16:43:27,243: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.158.108:5000]
[2024-03-26 16:43:27,243: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-26 16:43:29,240: INFO: _internal: 127.0.0.1 - - [26/Mar/2024 16:43:29] "GET / HTTP/1.1" 200 -]
[2024-03-26 16:43:37,426: INFO: _internal: 127.0.0.1 - - [26/Mar/2024 16:43:37] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 09:14:51,619: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.11.99:8080]
[2024-03-27 09:14:51,621: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-27 09:14:54,094: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 09:14:54] "GET / HTTP/1.1" 200 -]
[2024-03-27 09:16:21,878: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 09:16:21] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 09:45:44,588: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.120.108:8080]
[2024-03-27 09:45:44,588: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-27 09:45:46,289: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 09:45:46] "GET / HTTP/1.1" 200 -]
[2024-03-27 09:47:27,743: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 09:47:27] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 09:47:36,880: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 09:47:36] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 10:38:08,493: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.158.108:8080]
[2024-03-27 10:38:08,493: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-27 10:38:11,545: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:38:11] "GET / HTTP/1.1" 200 -]
[2024-03-27 10:38:30,316: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:38:30] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 10:39:01,740: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:39:01] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 10:40:23,820: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:40:23] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 10:40:34,801: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:40:34] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 10:40:43,521: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001F639E44280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-27 10:40:43,530: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:40:43] "POST /predict HTTP/1.1" 200 -]
[2024-03-27 10:42:01,600: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-27 10:42:01,618: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 10:42:01,633: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 10:42:01,637: INFO: common: created directory at: artifacts]
[2024-03-27 10:42:01,639: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-27 10:42:01,640: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 10:42:26,891: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-27 10:42:28,366: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-27 10:42:28,367: INFO: main: *******************]
[2024-03-27 10:42:28,368: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-27 10:42:28,373: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 10:42:28,376: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 10:42:28,378: INFO: common: created directory at: artifacts]
[2024-03-27 10:42:28,379: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-27 10:42:29,175: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-27 10:42:29,538: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-27 10:42:29,538: INFO: main: *******************]
[2024-03-27 10:42:29,540: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-27 10:42:29,545: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 10:42:29,548: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 10:42:29,550: INFO: common: created directory at: artifacts]
[2024-03-27 10:42:29,552: INFO: common: created directory at: artifacts\training]
[2024-03-27 10:45:33,737: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-27 10:45:33,737: INFO: main: *******************]
[2024-03-27 10:45:33,738: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-27 10:45:33,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 10:45:33,743: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 10:45:33,745: INFO: common: created directory at: artifacts]
[2024-03-27 10:45:48,758: INFO: common: json file saved at: scores.json]
[2024-03-27 10:45:48,759: INFO: common: json file saved at: scores.json]
[2024-03-27 10:45:48,760: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-27 10:45:49,432: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:45:49] "GET /train HTTP/1.1" 200 -]
[2024-03-27 10:45:49,480: INFO: _internal: 127.0.0.1 - - [27/Mar/2024 10:45:49] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-04-07 16:46:21,142: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.102.108:8080]
[2024-04-07 16:46:21,143: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-07 16:46:23,708: INFO: _internal: 127.0.0.1 - - [07/Apr/2024 16:46:23] "GET / HTTP/1.1" 200 -]
[2024-04-07 16:46:52,129: INFO: _internal: 127.0.0.1 - - [07/Apr/2024 16:46:52] "POST /predict HTTP/1.1" 200 -]
[2024-04-10 12:48:33,208: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-04-10 12:48:33,210: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-02 18:03:49,412: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-02 18:03:49,413: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-02 18:03:54,502: INFO: _internal: 127.0.0.1 - - [02/May/2024 18:03:54] "GET / HTTP/1.1" 200 -]
[2024-05-08 09:42:42,621: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.227.108:8080]
[2024-05-08 09:42:42,622: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 09:42:45,268: INFO: _internal: 127.0.0.1 - - [08/May/2024 09:42:45] "GET / HTTP/1.1" 200 -]
[2024-05-08 09:43:08,644: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-08 09:43:08,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 09:43:08,658: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 09:43:08,659: INFO: common: created directory at: artifacts]
[2024-05-08 09:43:08,661: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 09:43:08,663: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 09:43:20,138: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 09:43:20,971: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-08 09:43:20,972: INFO: main: *******************]
[2024-05-08 09:43:20,972: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-08 09:43:20,975: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 09:43:20,978: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 09:43:20,979: INFO: common: created directory at: artifacts]
[2024-05-08 09:43:20,980: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-08 09:43:21,557: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-08 09:43:21,798: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-08 09:43:21,799: INFO: main: *******************]
[2024-05-08 09:43:21,800: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-08 09:43:21,803: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 09:43:21,805: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 09:43:21,807: INFO: common: created directory at: artifacts]
[2024-05-08 09:43:21,808: INFO: common: created directory at: artifacts\training]
[2024-05-08 09:43:59,333: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-08 09:43:59,334: INFO: main: *******************]
[2024-05-08 09:43:59,335: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-08 09:43:59,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 09:43:59,340: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 09:43:59,342: INFO: common: created directory at: artifacts]
[2024-05-08 09:44:11,119: INFO: common: json file saved at: scores.json]
[2024-05-08 09:44:11,121: INFO: common: json file saved at: scores.json]
[2024-05-08 09:44:11,121: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-08 09:44:11,717: INFO: _internal: 127.0.0.1 - - [08/May/2024 09:44:11] "GET /train HTTP/1.1" 200 -]
[2024-05-08 09:44:11,753: INFO: _internal: 127.0.0.1 - - [08/May/2024 09:44:11] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-05-08 18:28:16,037: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:28:16,038: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:28:18,871: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:28:18] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:28:41,925: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:28:41] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:28:55,215: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:28:55] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:29:25,379: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:29:25] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:29:31,800: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:29:31] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:35:32,281: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:35:32,284: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:35:34,452: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:35:34] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:35:41,820: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:35:41] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:35:48,961: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:35:48] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:36:02,004: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:36:02] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:36:07,993: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:36:07] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:36:14,459: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000018B8174E3A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-05-08 18:36:14,469: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:36:14] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:38:02,184: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:38:02,185: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:38:04,012: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:38:04] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:38:25,058: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-08 18:38:25,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:38:25,079: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:38:25,081: INFO: common: created directory at: artifacts]
[2024-05-08 18:38:25,083: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 18:38:25,085: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 18:38:59,507: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 18:39:01,084: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-08 18:39:01,086: INFO: main: *******************]
[2024-05-08 18:39:01,087: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-08 18:39:01,095: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:39:01,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:39:01,104: INFO: common: created directory at: artifacts]
[2024-05-08 18:39:01,109: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-08 18:39:01,874: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-08 18:39:02,509: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-08 18:39:02,509: INFO: main: *******************]
[2024-05-08 18:39:02,510: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-08 18:39:02,515: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:39:02,518: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:39:02,520: INFO: common: created directory at: artifacts]
[2024-05-08 18:39:02,522: INFO: common: created directory at: artifacts\training]
[2024-05-08 18:41:43,478: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-08 18:41:43,478: INFO: main: *******************]
[2024-05-08 18:41:43,479: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-08 18:41:43,482: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 18:41:43,485: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 18:41:43,487: INFO: common: created directory at: artifacts]
[2024-05-08 18:41:57,677: INFO: common: json file saved at: scores.json]
[2024-05-08 18:41:57,680: INFO: common: json file saved at: scores.json]
[2024-05-08 18:41:57,680: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-08 18:41:58,359: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:41:58] "GET /train HTTP/1.1" 200 -]
[2024-05-08 18:41:58,403: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:41:58] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-05-08 18:42:18,835: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:42:18] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:42:24,411: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 42, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model (1).h5
[2024-05-08 18:42:24,451: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:42:24] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-08 18:43:23,284: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:43:23,285: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:43:25,665: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:43:25] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:43:33,305: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:43:33] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:43:46,752: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:43:46] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:43:56,055: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:43:56] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:44:10,484: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:44:10] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:48:40,004: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:48:40,005: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:48:41,550: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:48:41] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:48:50,379: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:48:50] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:48:56,733: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:48:56] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:49:52,674: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:49:52,674: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:49:54,871: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:49:54] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:50:01,310: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:50:01] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:50:24,326: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:50:24] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:50:31,960: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:50:31] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:50:38,556: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:50:38] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:51:00,867: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000267E7AB5280> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-05-08 18:51:00,878: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:51:00] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:51:06,960: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000267E77699D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-05-08 18:51:06,977: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:51:06] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:52:20,147: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:52:20,149: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:52:22,431: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:52:22] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:52:28,919: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:52:28] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:52:35,996: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:52:35] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:53:28,701: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:53:28,703: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:53:31,570: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:53:31] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:53:37,482: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:53:37] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:53:43,243: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:53:43] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:54:06,472: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:54:06] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:57:07,554: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 18:57:07,555: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 18:57:14,190: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:57:14] "GET / HTTP/1.1" 200 -]
[2024-05-08 18:57:20,093: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:57:20] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 18:57:29,104: INFO: _internal: 127.0.0.1 - - [08/May/2024 18:57:29] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 19:00:57,848: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 19:00:57,849: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 19:00:59,512: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:00:59] "GET / HTTP/1.1" 200 -]
[2024-05-08 19:01:05,482: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:01:05] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 19:01:11,956: INFO: _internal: 127.0.0.1 - - [08/May/2024 19:01:11] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 20:56:35,810: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 20:56:35,810: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 20:56:39,412: INFO: _internal: 127.0.0.1 - - [08/May/2024 20:56:39] "GET / HTTP/1.1" 200 -]
[2024-05-08 20:57:08,948: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-08 20:57:08,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 20:57:08,974: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 20:57:08,976: INFO: common: created directory at: artifacts]
[2024-05-08 20:57:08,978: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 20:57:08,979: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:02:49,090: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:02:50,749: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-08 21:02:50,751: INFO: main: *******************]
[2024-05-08 21:02:50,751: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-08 21:02:50,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:02:50,762: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:02:50,764: INFO: common: created directory at: artifacts]
[2024-05-08 21:02:50,766: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-08 21:02:51,510: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-08 21:02:51,897: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-08 21:02:51,898: INFO: main: *******************]
[2024-05-08 21:02:51,898: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-08 21:02:51,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:02:51,908: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:02:51,909: INFO: common: created directory at: artifacts]
[2024-05-08 21:02:51,911: INFO: common: created directory at: artifacts\training]
[2024-05-08 21:10:08,733: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-08 21:10:08,734: INFO: main: *******************]
[2024-05-08 21:10:08,734: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-08 21:10:08,737: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:10:08,741: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:10:08,742: INFO: common: created directory at: artifacts]
[2024-05-08 21:10:23,790: INFO: common: json file saved at: scores.json]
[2024-05-08 21:10:23,792: INFO: common: json file saved at: scores.json]
[2024-05-08 21:10:23,792: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-08 21:10:24,398: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:10:24] "GET /train HTTP/1.1" 200 -]
[2024-05-08 21:11:45,740: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 21:11:45,741: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 21:11:55,015: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:11:55] "GET / HTTP/1.1" 200 -]
[2024-05-08 21:12:01,776: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:12:01] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 21:12:16,644: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:12:16] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 21:12:29,010: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:12:29] "POST /predict HTTP/1.1" 200 -]
[2024-05-08 21:15:18,052: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 21:15:18,053: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 21:15:20,101: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:15:20] "GET / HTTP/1.1" 200 -]
[2024-05-08 21:15:40,279: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-08 21:15:40,285: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:15:40,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:15:40,300: INFO: common: created directory at: artifacts]
[2024-05-08 21:15:40,302: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 21:15:40,303: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:18:45,590: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:18:45] "GET /train HTTP/1.1" 200 -]
[2024-05-08 21:19:12,810: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 21:19:12,810: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 21:19:15,332: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:19:15] "GET / HTTP/1.1" 200 -]
[2024-05-08 21:19:34,019: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-08 21:19:34,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:19:34,029: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:19:34,031: INFO: common: created directory at: artifacts]
[2024-05-08 21:19:34,034: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 21:19:34,035: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:24:47,182: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:24:48,959: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-08 21:24:48,961: INFO: main: *******************]
[2024-05-08 21:24:48,961: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-08 21:24:48,966: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:24:48,970: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:24:48,973: INFO: common: created directory at: artifacts]
[2024-05-08 21:24:48,976: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-08 21:24:49,860: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-08 21:24:50,802: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-08 21:24:50,804: INFO: main: *******************]
[2024-05-08 21:24:50,804: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-08 21:24:50,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:24:50,816: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:24:50,818: INFO: common: created directory at: artifacts]
[2024-05-08 21:24:50,820: INFO: common: created directory at: artifacts\training]
[2024-05-08 21:24:56,319: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "main.py", line 33, in <module>
      model_trainer.main()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model_trainer.main()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "main.py", line 33, in <module>
      model_trainer.main()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2024-05-08 21:24:57,054: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:24:57] "GET /train HTTP/1.1" 200 -]
[2024-05-08 21:31:57,119: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.21.0.159:8080]
[2024-05-08 21:31:57,120: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 21:32:00,398: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:32:00] "GET / HTTP/1.1" 200 -]
[2024-05-08 21:32:30,472: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-08 21:32:30,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:32:30,485: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:32:30,487: INFO: common: created directory at: artifacts]
[2024-05-08 21:32:30,489: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 21:32:30,490: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:39:57,514: ERROR: main: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))]
Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 737, in _error_catcher
    yield
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 852, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 835, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\hp\anaconda3\envs\kidney\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 1033, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 925, in read
    data = self._raw_read(amt)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 881, in _raw_read
    self._fp.close()
  File "C:\Users\hp\anaconda3\envs\kidney\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\urllib3\response.py", line 754, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\gdown\download.py", line 344, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
[2024-05-08 21:39:58,564: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:39:58] "GET /train HTTP/1.1" 200 -]
[2024-05-08 21:40:27,508: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-08 21:40:27,511: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-08 21:40:31,062: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:40:31] "GET / HTTP/1.1" 200 -]
[2024-05-08 21:40:50,905: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-08 21:40:50,912: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:40:50,917: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:40:50,921: INFO: common: created directory at: artifacts]
[2024-05-08 21:40:50,923: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-08 21:40:50,925: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:41:55,973: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-08 21:41:57,850: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-08 21:41:57,851: INFO: main: *******************]
[2024-05-08 21:41:57,851: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-08 21:41:57,856: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:41:57,861: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:41:57,863: INFO: common: created directory at: artifacts]
[2024-05-08 21:41:57,866: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-08 21:41:58,631: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-08 21:41:59,275: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-08 21:41:59,276: INFO: main: *******************]
[2024-05-08 21:41:59,277: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-08 21:41:59,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-08 21:41:59,288: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-08 21:41:59,290: INFO: common: created directory at: artifacts]
[2024-05-08 21:41:59,330: INFO: common: created directory at: artifacts\training]
[2024-05-08 21:42:05,188: ERROR: main: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "main.py", line 33, in <module>
      model_trainer.main()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    model_trainer.main()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
    training.train()
  File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
    self.model.fit(
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'AssignVariableOp_1' defined at (most recent call last):
    File "main.py", line 33, in <module>
      model_trainer.main()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\pipeline\stage_03_model_training.py", line 21, in main
      training.train()
    File "c:\users\hp\onedrive\desktop\sgp\kidney-disease-classification-deep-learning\src\cnnClassifier\components\model_training.py", line 76, in train
      self.model.fit(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\engine\training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 543, in minimize
      self.apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1174, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 650, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1200, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1250, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 1247, in apply_grad_to_update_var
      return self._update_step(grad, var)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\optimizer.py", line 240, in _update_step
      self.update_step(gradient, variable)
    File "C:\Users\hp\anaconda3\envs\kidney\lib\site-packages\keras\optimizers\sgd.py", line 179, in update_step
      m.assign(-gradient * lr + m * momentum)
Node: 'AssignVariableOp_1'
Trying to assign to variable with tensor with wrong shape. Expected [1] got [2]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference_train_function_1463]
[2024-05-08 21:42:05,912: INFO: _internal: 127.0.0.1 - - [08/May/2024 21:42:05] "GET /train HTTP/1.1" 200 -]
[2024-05-09 16:46:55,832: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-09 16:46:55,833: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 16:46:59,010: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:46:59] "GET / HTTP/1.1" 200 -]
[2024-05-09 16:47:04,470: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:47:04] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 16:47:15,062: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:47:15] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 16:49:42,794: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-09 16:49:42,794: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 16:49:45,228: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:49:45] "GET / HTTP/1.1" 200 -]
[2024-05-09 16:49:45,366: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:49:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2024-05-09 16:53:14,937: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-09 16:53:14,937: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 16:53:17,178: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:53:17] "GET / HTTP/1.1" 200 -]
[2024-05-09 16:53:21,620: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:53:21] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 16:55:20,075: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.29.55.108:8080]
[2024-05-09 16:55:20,077: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-09 16:55:21,525: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:55:21] "GET / HTTP/1.1" 200 -]
[2024-05-09 16:55:26,584: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:55:26] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 16:55:36,497: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:55:36] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 16:55:37,417: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:55:37] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 16:55:38,270: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:55:38] "POST /predict HTTP/1.1" 200 -]
[2024-05-09 16:55:41,620: INFO: _internal: 127.0.0.1 - - [09/May/2024 16:55:41] "POST /predict HTTP/1.1" 200 -]
